baseURL = 'https://jwtanner.com/'
locale = 'en-US'
title = 'Justin Tanner'
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
disableKinds = ['taxonomy', 'term']

[params]
  author = 'Justin Tanner'
  github = 'https://github.com/justintanner'
  og_image = '/og.jpg'
  sitename = 'Justin Tanner: AI Agent Builder'

[markup.goldmark.renderer]
  unsafe = true
