baseURL = 'https://jwtanner.com/'
languageCode = 'en-us'
title = 'Justin Tanner: Computer Programmer'
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
