baseURL = 'http://jwtanner.com/'
languageCode = 'en-us'
title = 'Justin Tanner'
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
disableKinds = ['taxonomy', 'term']

[params]
  author = 'Justin Tanner'
  github = 'https://github.com/justintanner'
  og_image = '/og.png'
  sitename = 'Justin Tanner: Computer Programmer'

